# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='persmission',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='persmission',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='permissiongroup',
            old_name='persmission',
            new_name='permission',
        ),
    ]
